### ISSUE TITLE
Let me know if you want any input

### ISSUE THREAD

**Issue by JedMeister** [trollByte/turnkeyELK#2]
Apologies on abusing your new project's "issues" but I could see no other easy way of making contact with you...

This looks like a really Interesting project. Let me know if you want any input. I know absolutely nothing about the software that you are integrating but I'm responsible for adding new apps to the library so I maybe able to give you TurnKey specific advice/guidance. 

If you haven't already I strongly advise that you read the [TKLDev documentation](https://github.com/turnkeylinux-apps/tkldev/tree/master/docs); particularly the page on [new appliances](https://github.com/turnkeylinux-apps/tkldev/blob/master/docs/development/new.rst).

**Comment by trollByte** [comment]
No worries.  I apologize if I did not provide an easy way to contact me. Thank you for reaching out!

Email: uberstring@gmail.com

Yes, I will be asking for some advice.  What would be the best way to contact you?

**Comment by JedMeister** [comment]
No problems at all! :+1: 

FWIW I've opened a new "new appliance" issue on the tracker re this proposed appliance: https://github.com/turnkeylinux/tracker/issues/610

That might be a good place for discussion related to this appliance build? Otherwise, our [forums](https://www.turnkeylinux.org/forum) are another good place for discussion. I try to keep up to things on the forums but I must admit that they sometimes get out of hand and I can be a bit slow to respond... If you post and don't get a timely response please feel free to bump your thread and/or give me a nudge via email.

If you think that you've encountered a TurnKey bug or some documentation that isn't clear then please open a new issue on the [tracker](https://github.com/turnkeylinux/tracker/issues).

Having said that, mentioning me anywhere on GitHub will get my attention! So if you'd rather just use your issues here that's fine by me. Just explicitly mention me when you want my input! :smile: 

I prefer to do as much communication as I can in public (reduces the need to repeat myself over and over! :smile:) but if it's something that you need to discuss privately (or as I said; you're not getting a timely response) then shoot me an email: jeremy@turnkeylinux.org
